FROM python:3.10.14-slim-bookworm

# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  wget \
  bzip2 \
  ca-certificates \
  build-essential \
  portaudio19-dev \ 
  cmake \
  git \
  mesa-vulkan-drivers \
  vulkan-tools \
  libvulkan-dev \
  spirv-tools \
  libvulkan1 \
  && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --break-system-packages --no-cache-dir -r requirements.txt

RUN pip install --upgrade pip setuptools
RUN pip uninstall -y llama-cpp-python
ENV CMAKE_ARGS="-DGGML_VULKAN=on"
RUN pip install --force-reinstall --ignore-installed --no-cache-dir --no-deps llama-cpp-python==0.3.8

# Copy the source contents into the container at /app
COPY ./src /app/src

ENV AISERVER_LLM_MODEL_NAME=None
ENV AISERVER_TTS_MODEL_NAME=None
ENV AISERVER_STT_MODEL_NAME=None
ENV AISERVER_EMBED_MODEL_NAME=None
ENV AISERVER_USE_DISK_CACHE=False
ENV AISERVER_HOST=0.0.0.0
ENV AISERVER_PORT=8080

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run AIServer when the container launches
CMD ["python", "src/AIServerInternal.py"]