# fly.toml app configuration file generated for elite-dangerous-ai-integration-empty-river-9141 on 2024-11-02T16:11:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elite-dangerous-ai-integration-empty-river-9141'
primary_region = 'ord'

[build]
  dockerfile = './Dockerfile.nv'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1
    soft_limit = 1

[[vm]]
  size = 'l40s'
